services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      FRONTEND_PORT: 8080
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      BACKEND_PORT: 5000